import Link from "next/link";

export const metadata = {
  title: "Terms of Service — dailyforge·ai",
  description: "The terms under which you can use dailyforge·ai.",
};

const CONTACT_EMAIL = "connect@codingryder.com";

export default function TermsPage() {
  return (
    <article className="mx-auto max-w-3xl px-4 sm:px-6 py-8 sm:py-16 prose prose-zinc dark:prose-invert">
      <h1 className="text-2xl sm:text-3xl font-semibold tracking-tight">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mt-2">Last updated: 26 June 2026</p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">1. Who we are</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        dailyforge·ai (&quot;we&quot;, &quot;us&quot;) is a collection of free online tools operated by Coding Ryder. By using the site you agree to these terms.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">2. The service</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        We provide utility tools for converting documents, editing images, and processing audio/video. Most tools are free to use without an account. Some tools have a fair-use rate limit that resets every few hours. We may add, remove, or change tools at any time.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">3. Acceptable use</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">You agree not to:</p>
      <ul className="mt-3 text-muted-foreground leading-relaxed list-disc pl-6 space-y-2">
        <li>Use the tools to create or distribute illegal content, including CSAM, non-consensual intimate imagery, or material that infringes others&apos; intellectual property.</li>
        <li>Process content you don&apos;t have the right to process (third-party copyrighted material, private documents that aren&apos;t yours, etc.).</li>
        <li>Attempt to bypass rate limits, scrape the site programmatically, or use automation that puts unreasonable load on our servers.</li>
        <li>Reverse-engineer, modify, or attempt to extract the source of the tools or their AI prompts.</li>
        <li>Use the service to develop competing AI services or train machine-learning models.</li>
      </ul>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        We may terminate access for users who violate these terms.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">4. Your content</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        You keep all rights to the content you upload or input. By using a tool, you grant us a limited, temporary license to process your content for the sole purpose of producing the requested output. We don&apos;t store your file contents, and we don&apos;t use them to train any model.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">5. AI outputs</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        Outputs from AI tools (summaries, translations, transcriptions, OCR, etc.) are generated by third-party models and can be inaccurate. You are responsible for reviewing any output before relying on it for important decisions. We make no warranty as to accuracy or fitness for purpose.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">6. Accounts</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        If you create an account, you&apos;re responsible for keeping it secure. We&apos;re not liable for losses caused by unauthorized access. You can delete your account at any time by emailing us; we&apos;ll remove your account record and any logs tied to it within 30 days.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">7. Service availability</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        We aim for the site to be available, but we make no uptime guarantee. The service is provided &quot;as is&quot; without warranties of any kind, express or implied.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">8. Limitation of liability</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        To the maximum extent permitted by law, dailyforge·ai is not liable for indirect, incidental, consequential, or special damages arising from your use of the site or any tool, including lost data, lost profits, or business interruption. Our total liability for any claim is limited to the amount you paid us in the past 12 months, which for the free service is zero.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">9. Third parties</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        The site relies on third-party providers (listed in our{" "}
        <Link href="/privacy" className="underline">privacy policy</Link>). Their terms also apply when their services are used. We are not responsible for outages or changes on their side.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">10. Advertising</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        Some pages may display ads from third-party networks (e.g. Google AdSense). We don&apos;t endorse advertised products, and you interact with advertisers at your own risk.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">11. Changes to these terms</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        We may update these terms as the service evolves. Continuing to use the site after a change means you accept the updated terms.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">12. Governing law</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        These terms are governed by the laws of India. Disputes will be handled in the courts of Bangalore, Karnataka.
      </p>

      <h2 className="text-lg sm:text-xl font-semibold tracking-tight mt-10">Contact</h2>
      <p className="mt-3 text-muted-foreground leading-relaxed">
        Questions? Email{" "}
        <a href={`mailto:${CONTACT_EMAIL}`} className="underline">{CONTACT_EMAIL}</a>.
      </p>

      <p className="mt-10 text-sm">
        <Link href="/" className="underline text-muted-foreground hover:text-foreground">← Back to home</Link>
      </p>
    </article>
  );
}
